#!/usr/bin/env sh

exec </dev/tty

while true; do
    read -p "[migration generator] Migration name? " name

    if [ "$name" = "" ]; then
        echo "Migration name cannot be empty"
        exit 1
    fi

    node -r tsconfig-paths/register ./node_modules/typeorm/cli-ts-node-commonjs.js -d src/database migration:generate -p src/database/migrations/$name
    break

done
