version: "3.5"

services:
    postgres:
        container_name: price_checker_postgres
        image: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
            POSTGRES_DB: ${POSTGRES_DB:-price_checker}
            PGDATA: /data/postgres
        ports:
            - "5434:5432"
        networks:
            - postgres
        restart: unless-stopped

networks:
    postgres:
        driver: bridge
